name: Docker Deploy

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}  # Set this in your repo secrets
          password: ${{ secrets.DOCKERHUB_TOKEN }}  # Set this in your repo secrets

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true  # Set to true to push the image to Docker Hub
          tags: niansuh/incubator-answer:latest  # Change this to your image name

      - name: Logout from Docker Hub
        run: docker logout
